[
    {
        "userID":"554",
        "firstName":"Zenande",
        "lastName":"Nocanda",
        "email":"zenandenocanda16@gmail.com",
        "registrationDate":"29/01/2024",
    },
    {
        "userID":"222",
        "firstName":"Asiphe",
        "lastName":"Dumzela",
        "email":"asiphesonadumzela31@gmail.com",
        "registrationDate":"02/02/2024",
    },
    {
        "userID":"242",
        "firstName":"Siyavuya",
        "lastName":"Khohlani",
        "email":"Siyavuyakhohlani2@gmail.com",
        "registrationDate":"17/02/2024",
    },
    {
        "userID":"477",
        "firstName":"Sivuyile",
        "lastName":"Mtwetwe",
        "email":"sivuyilemtwetwe@gmail.com",
        "registrationDate":"22/01/2024",
    },
    {
        "userId":"711",
        "firstName":"Usisipho",
        "lastName":"Mxinwa",
        "email":"usimxi711@gmail.com",
        "registrationDate":"02/02/2024",
    },
    {
        "userID":"229",
        "firstName":"Avela",
        "lastName":"Nikani",
        "email":"avelarnikani47@gmail.com",
        "registrationDate":"28/01/2024",
    }
]
